<a href="https://colab.research.google.com/github/ferbits/Laboratorio7/blob/main/Laboratorio7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
PARTE UNO DEL LABORATORIO 7

#Crear un DataFrame con los nombres, profesión y países de 8 personas, y luego imprimir el DataFrame.

In [ ]:
import pandas as pd
data = {'Nombre': ['José', 'Natalia', 'Mariana', 'Samuel','Liliana','Joan','Andrés','Jordan'],
        'Profesión': ['Contador', 'Ingeniero', 'Médico','Profesor','Arquitecto','Diseñador','Biologo','Abogado'],
        'País': ['Colombia', 'Perú', 'Estados Unidos', 'Argentina','Paraguay','Ecuador','Venezuela','España']}
df = pd.DataFrame(data)
print(df)

    Nombre   Profesión            País
0     José    Contador        Colombia
1  Natalia   Ingeniero            Perú
2  Mariana      Médico  Estados Unidos
3   Samuel    Profesor       Argentina
4  Liliana  Arquitecto        Paraguai
5     Joan   Diseñador         Ecuador
6   Andrés     Biologo       Venezuela
7   Jordan     Abogado          España


#**Cargar un archivo CSV ** **texto en negrita** **texto en negrita**

In [ ]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/autor.csv')
print(df.head(5))

   id_autor            nombre_autor nacionalidad_autor
0         1  Gabriel García Marquez         Colombiano
1         2             Tim Harford          Británico
2         3         Daniel Kahneman            Israelí
3         4              Dan Ariely     Estadounidense
4         5  Miguel de Cervantes S.            Español


#**Crear un DataFrame con valores aleatorios**

In [ ]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.rand(100,8))
df.describe()

0           1           2           3           4           5  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean     0.469636    0.485322    0.519619    0.482950    0.489604    0.464131   
std      0.296118    0.317302    0.318259    0.283131    0.298493    0.278979   
min      0.004997    0.002661    0.007810    0.006373    0.000250    0.030842   
25%      0.188940    0.197512    0.243737    0.245153    0.206520    0.217522   
50%      0.469138    0.473016    0.563169    0.513527    0.514758    0.459073   
75%      0.729201    0.789161    0.809056    0.708239    0.749766    0.683965   
max      0.981956    0.982142    0.988894    0.989322    0.997252    0.999461   

                6           7  
count  100.000000  100.000000  
mean     0.468467    0.475226  
std      0.276370    0.283750  
min      0.001460    0.001573  
25%      0.238599    0.239025  
50%      0.447383    0.482307  
75%      0.688867    0.740761  
max      0.989461    0.998301

**PARTE 2 DEL LABORATORIO 7**

In [ ]:
# Importamos la librería numpy
import numpy as np

# Creamos un array de números del 1 al 10
numeros = np.arange(1, 11)

# Calculamos la suma de todos los elementos del array
suma = np.sum(numeros)

# Calculamos la media de todos los elementos del array
media = np.mean(numeros)

# Obtenemos el valor máximo del array
valor_maximo = np.max(numeros)

# Mostramos los resultados
print("Array de números:", numeros)
print("Suma:", suma)
print("Media:", media)
print("Valor máximo:", valor_maximo)

Array de números: [ 1  2  3  4  5  6  7  8  9 10]
Suma: 55
Media: 5.5
Valor máximo: 10


Arreglo de 3 por 4 lleno de ceros con posterior modificación.

In [ ]:
import numpy as np  # Importamos la biblioteca numpy para trabajar con arrays

# Creamos un array de 3x4 lleno de ceros
arreglo_1=np.zeros((3,4))
print("Arreglo original 3x4:")
print(arreglo_1)

# Cambiamos la forma del array a 2x6
arreglo_2=arreglo_1.reshape(2,6)
print("\nArreglo cambiado a la forma 2x6:")
print(arreglo_2)

Arreglo original 3x4:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Arreglo cambiado a la forma 2x6:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


Matriz Traspuesta

In [ ]:
# Importamos la librería numpy y la nombramos como np para simplificar el uso
# de sus funciones
import numpy as np

# Generamos una matriz aleatoria de 3x3 con valores entre 0 y 1
matriz =np.random.rand(3,3)
print("Matriz original:")
print(matriz)

# Calculamos la transpuesta de la matriz
matriz_transpuesta =matriz.T
print("\nMatriz transpuesta:")
print(matriz_transpuesta)

Matriz original:
[[0.08398873 0.95638618 0.96482561]
 [0.84971334 0.77486281 0.63214301]
 [0.59253673 0.21203134 0.76696098]]

Matriz transpuesta:
[[0.08398873 0.84971334 0.59253673]
 [0.95638618 0.77486281 0.21203134]
 [0.96482561 0.63214301 0.76696098]]


Concatena dos arreglos

In [ ]:
import numpy as np  # Importamos la biblioteca NumPy, que nos permite trabajar con arrays y operaciones
#matemáticas.

# Creamos dos arrays de NumPy con 5 valores cada uno.
arreglo_1 = np.array([1, 2, 3, 4, 5])
arreglo_2 = np.array([6, 7, 8, 9, 10])

# Concatenamos los dos arrays usando la función np.concatenate y guardamos el resultado en una nueva
#variable.
arreglo_concatenado = np.concatenate((arreglo_1, arreglo_2))

# Imprimimos el array concatenado.
print("Arreglo concatenado:", arreglo_concatenado)

Arreglo concatenado: [ 1  2  3  4  5  6  7  8  9 10]
